learning_logs/urls.py
from django.conf.urls import url

from . import views

app_name = 'learning_logs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
        name='edit_entry'),
    url(r'^del_entry/(?P<entry_id>\d+)/$', views.del_entry,
        name='del_entry'),
    url(r'^new_entry2/(?P<topic_id>\d+)/$', views.new_entry2, name='new_entry2'),
    url(r'^edit_entry2/(?P<entry_id>\d+)/$', views.edit_entry2,
        name='edit_entry2'),
    url(r'^topic/api$', views.topic_api, name='topic_api'),
    url(r'^entry/api$', views.entry_api, name='entry_api'),
    url(r'^new_entry/api$', views.new_entry_api, name='new_entry_api'),
    url(r'^new_topic/api$', views.new_topic_api, name='new_topic_api')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^api', views.user_api, name='user_api'),
    url(r'^last_login/api', views.last_login_api, name='last_login_api')
]

xianyu/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', xadmin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^', include('message_board.urls', namespace='message_board')),
    url(r'^', include('introduce.urls', namespace='introduce')),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from .forms import RegisterForm
import datetime

from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response

from django.contrib.auth.models import User
from .serializers import *


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            successful = '<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a><strong>注册成功!</strong> 并已为你自动登录</div>'
            return render(request, 'users/register.html', {"successful": successful})
        else:
            error_register = '<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a><strong>注册失败!</strong> 原因可能是用户名已被注册或者两次密码输入不相同</div>'
            return render(request, 'users/register.html', {"error_register": error_register})

    context = {'form': form}
    return render(request, 'users/register.html', context)


@api_view(['GET', 'POST'])
def user_api(request):
    # if request.method == 'GET':
    #     content = User.objects.all()
    #     serializer = UserSerializer(content, many=True)
    #     return Response(serializer.data)
    if request.method == 'POST':
        content = User.objects.all()
        serializer = UserSerializer(content, many=True)
        for i in serializer.data:
            if request.data['username'] == i['username']:
                authenticated_user = authenticate(username=request.data['username'], password=request.data['password'])
                if authenticated_user:
                    date = datetime.datetime.now()
                    User.objects.filter(username=request.data['username']).update(last_login=date)
                    return Response({'isLogin': True, 'userId': i['id']})
                else:
                    return Response('登录失败')
        return Response('无此用户')


@api_view(['GET', 'POST'])
def last_login_api(request):
    if request.method == 'POST':
        date = datetime.datetime.now()
        User.objects.filter(username=request.data['username']).update(last_login=date)
        return Response()

users/templates/users/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>登录你的帐号</h2>
{% endblock %}

{% block content %}
   <div style="width:400px;margin:0 auto;">
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="button button-rounded button-inverse">登录</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
   <div style="width:400px;margin:0 auto;text-align:left;">
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label" for="id_username">用户名</label>
            <input name="username" id="id_username" class="form-control" placeholder="请输入用户名" maxlength="254" autofocus="" required="" type="text">
            <span class="helptext"></span>
            <ul>
                <li>用户名需小于150个字符。</li>
                <li>用户名可以使用汉字、字母、数字和部分符号(@/./+/-/_)。</li>
            </ul>
        </div>

        <div class="form-group">
            <label class="control-label" for="id_password1">密码</label>
            <input id="id_password1" name="password1" placeholder="请输入密码" class="form-control" required="" type="password">
        <span class="helptext"></span>
        <ul>
            <li>你的密码不能与其他个人信息太相似。</li>
            <li>你的密码必须包含至少 8 个字符。</li>
            <li>你的密码不能是大家都爱用的常见密码。</li>
            <li>你的密码不能全部为数字。</li>
        </ul>
        </div>


        <div class="form-group">
            <label class="control-label" for="id_password2">确认密码</label>
            <input id="id_password2" name="password2" placeholder="请再次输入密码" class="form-control" required="" type="password">
            <span class="helptext"></span>
            <ul>
                <li>为了校验，请输入与上面相同的密码。</li>
            </ul>
        </div>

        <div class="form-group">
            <label class="control-label" for="id_email">邮箱</label>
            <input id="id_email" name="email" placeholder="请输入邮箱" class="form-control" type="email" onFocus="if(value==defaultValue){value='';this.style.color='#000'}" onBlur="if(!value){value=defaultValue; this.style.color='#999'}" style="color:#999">
            <span class="helptext"></span>
        <ul>
            <li>邮箱可以不填。</li>
        </ul>
        </div>
<div style="text-align:center">
        <button id="register" class="button button-rounded button-inverse" name="submit">注册</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </div>
    </form>
   </div>

    <br/>
        {% autoescape off %}
        {{ error_register }}
        {{ successful }}
        {% endautoescape %}

{% endblock content %}