message_board/urls.py
from django.conf.urls import url

from . import views

app_name = 'message_board'

urlpatterns = [
    url(r'^message_board/$', views.message_board, name='message_board'),
    url(r'^message_board/api$', views.message_board_api, name='message_board_api'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^api', views.user_api, name='user_api'),
    url(r'^last_login/api', views.last_login_api, name='last_login_api')
]

xianyu/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', xadmin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^', include('message_board.urls', namespace='message_board')),
    url(r'^', include('introduce.urls', namespace='introduce')),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message_board/models.py
from django.db import models


class MessageBoard(models.Model):
    name = models.CharField(max_length=100, verbose_name="留言者")
    text = models.TextField(verbose_name="留言内容")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="留言时间")

    class Meta:
        verbose_name = u"留言"
        verbose_name_plural = u'留言'

    def __str__(self):
        return self.text

message_board/forms.py
from django import forms

from .models import MessageBoard


class MessageBoardForm(forms.ModelForm):
    class Meta:
        model = MessageBoard
        fields = ['name', 'text']

message_board/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response

from .models import *
from .forms import MessageBoardForm
from .serializers import *


def message_board(request):
    if request.method != 'POST':
        form = MessageBoardForm()
    else:
        form = MessageBoardForm(request.POST)
        if form.is_valid():
            message_board = form.save(commit=False)
            message_board.save()
            return HttpResponseRedirect(reverse('message_board:message_board'))

    message_board_list = MessageBoard.objects.filter()
    context = {'form': form,
               'message_board_list': message_board_list}

    return render(request, 'message_board.html', context)


@api_view(['GET', 'POST'])
def message_board_api(request):
    if request.method == 'GET':
        content = MessageBoard.objects.all()
        serializer = MesSerializer(content, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = MesSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

message_board/templates/message_board.html
{% extends "base.html" %}

{% block header %}
  <h1>留言板</h1>
{% endblock %}

{% block content %}

<ul class="list-unstyled">
  {% for message_board in message_board_list reversed %}
  <li>
    <div>
      #{{forloop.revcounter}}
    </div>
    <time class="submit-date">{{ message_board.created_time }}</time>
    <span class="nickname"> - <b>{{ message_board.name }}</b></span>
    <div class="text">
      {{ message_board.text }}
      <hr/>
    </div>
  </li>
  {% empty %}
  <h4>现在还没有任何留言</h4>
  {% endfor %}
</ul>

<br/>

<div style="width:350px;margin:0 auto;">
<form action="{% url 'message_board:message_board' %}" method="post">
  {% csrf_token %}
  <label for="id_name">昵称：</label>
      <br>
      <input name="name" maxlength="100" required="" id="id_name" type="text" class="form-control">
      <label for="id_text">留言：</label>
      <br/>
      <textarea name="text" cols="40" rows="10" required="" id="id_text" class="form-control" style="height:150px;"></textarea>
      <br/>
      <button id="message" type="submit" class="button button-rounded button-inverse">发表</button>
  </form>    <!-- row -->
</div>
{% endblock content %}