introduce/urls.py
from django.conf.urls import url

from . import views

app_name = 'introduce'

urlpatterns = [
    url(r'^update_log/$', views.update_log, name='update_log'),
    url(r'^about/$', views.about, name='about'),
    url(r'^tip/$', views.tip, name='tip'),
    url(r'^about/api/$', views.about_api, name='about_api'),
    url(r'^gamename/api$', views.gamename_api, name='gamename_api'),
    url(r'^update_log/api$', views.update_log_api, name='update_log_api'),
]

learning_logs/urls.py
from django.conf.urls import url

from . import views

app_name = 'learning_logs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
        name='edit_entry'),
    url(r'^del_entry/(?P<entry_id>\d+)/$', views.del_entry,
        name='del_entry'),
    url(r'^new_entry2/(?P<topic_id>\d+)/$', views.new_entry2, name='new_entry2'),
    url(r'^edit_entry2/(?P<entry_id>\d+)/$', views.edit_entry2,
        name='edit_entry2'),
    url(r'^topic/api$', views.topic_api, name='topic_api'),
    url(r'^entry/api$', views.entry_api, name='entry_api'),
    url(r'^new_entry/api$', views.new_entry_api, name='new_entry_api'),
    url(r'^new_topic/api$', views.new_topic_api, name='new_topic_api')
]

message_board/urls.py
from django.conf.urls import url

from . import views

app_name = 'message_board'

urlpatterns = [
    url(r'^message_board/$', views.message_board, name='message_board'),
    url(r'^message_board/api$', views.message_board_api, name='message_board_api'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^api', views.user_api, name='user_api'),
    url(r'^last_login/api', views.last_login_api, name='last_login_api')
]

xianyu/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', xadmin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^', include('message_board.urls', namespace='message_board')),
    url(r'^', include('introduce.urls', namespace='introduce')),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Topic(models.Model):
    text = models.CharField(max_length=200, verbose_name="主题名称")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="创建者")

    class Meta:
        verbose_name = u"主题"
        verbose_name_plural = u"主题"

    def __str__(self):
        return self.text


class Entry(models.Model):
    title = models.CharField(max_length=200, null=True, verbose_name="标题")
    text = RichTextUploadingField(verbose_name="内容")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="所属主题")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name="创建者")

    class Meta:
        verbose_name = u"内容"
        verbose_name_plural = u'内容'

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'text']
        labels = {'text': '', 'title': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from .serializers import *



def index(request):
    return render(request, 'index.html')


@login_required()
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)


@login_required()
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', context)


@login_required()
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        else:
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'new_topic.html', context)


@login_required()
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
        else:
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry.html', context)


@login_required()
def new_entry2(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry2.html', context)


@login_required()
def edit_entry2(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry2.html', context)


@login_required()
def del_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    Entry.objects.filter(id=entry_id).delete()
    return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry.html', context)


@api_view(['GET', 'POST'])
def topic_api(request):
    # if request.method == 'GET':
    #     content = Topic.objects.all()
    #     serializer = TopicSerializer(content, many=True)
    #     return Response(serializer.data)
    if request.method == 'POST':
        content = Topic.objects.filter(owner=request.data['userId']).order_by('date_added')
        serializer = TopicSerializer(content, many=True)
        return Response(serializer.data)


@api_view(['GET', 'POST'])
def entry_api(request):
    # if request.method == 'GET':
    #     content = Entry.objects.all()
    #     serializer = EntrySerializer(content, many=True)
    #     return Response(serializer.data)
    if request.method == 'POST':
        content = Entry.objects.filter(topic=request.data['topicId'])
        serializer = EntrySerializer(content, many=True)
        return Response(serializer.data)


@api_view(['GET', 'POST'])
def new_entry_api(request):
    # if request.method == 'GET':
    #     content = Entry.objects.all()
    #     serializer = EntrySerializer(content, many=True)
    #     return Response(serializer.data)
    if request.method == 'POST':
        serializer = EntrySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def new_topic_api(request):
    # if request.method == 'GET':
    #     content = Topic.objects.all()
    #     serializer = TopicSerializer(content, many=True)
    #     return Response(serializer.data)
    if request.method == 'POST':
        serializer = TopicSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)

learning_logs/templates/base.html
{% load bootstrap3 %}

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>非洲咸鱼</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="/static/new/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="/static/new/css/index.css" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="/static/new/css/buttons.css">
<script src="/static/new/js/jquery.min.js"></script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?26744f7ac6095574146b455320d83e36";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

{% bootstrap_javascript %}
</head>

<body>
<div class="full"> <span class="menu"></span>
  <div class="navbar" style="font-family:'SimSun'"> <a class="menu" href="#"> <i class="icon-align-justify"></i></a> <a class="link abt" href="{% url 'learning_logs:index'%}"> <span class="active"><span class="valign"><span class="vertical">首页</span></span></span><span class="hover"><span class="valign"><span class="vertical">HOME</span></span></span></a><a class="link abt" href="{% url 'introduce:about' %}"><span class="active"><span class="valign"><span class="vertical">游戏介绍</span></span></span><span class="hover"><span class="valign"><span class="vertical">ABOUT</span></span></span></a><a class="link abt" href="{% url 'introduce:update_log' %}"><span class="active"><span class="valign"><span class="vertical">更新日志</span></span></span><span class="hover"><span class="valign"><span class="vertical">UPDATE</span></span></span></a><a class="link abt" href="{% url 'learning_logs:topics' %}"><span class="active"><span class="valign"><span class="vertical">笔记</span></span></span><span class="hover"><span class="valign"><span class="vertical">TOPIC</span></span></span></a><a class="link abt" href="{% url 'message_board:message_board' %}"><span class="active"><span class="valign"><span class="vertical">留言板</span></span></span><span class="hover"><span class="valign"><span class="vertical">MESSAGE</span></span></span></a></div>
  <script>
		$( "span.menu" ).click(function() {
		  $( ".navbar" ).slideToggle( "slow", function() {
			// Animation complete.
		  });
		});
	</script>
  <div class="main">
    <div class="head">
      <div class="second-head">
      <h2>这是一个测试用的网站<br/><small style="color:#727272">或许还是<a href="{% url 'introduce:tip' %}" style="color:#727272">金傲城</a>的官网？</small></h2>
      </div>
    </div>
    <div class="txt1">
      <div class="second-head">
        {% block header %}{% endblock %}
        <hr/>
        {% block content %}{% endblock %}
      </div>
    </div>
        <div class="copyright">
      <p class="write">Copyright &copy; 非洲咸鱼</p>
    </div>
</div>
</div>
</body>
</html>

learning_logs/templates/edit_entry.html
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel" >&nbsp&nbsp标题:</h4>
</div>

<div class="modal-body" >
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        <textarea class="form-control" cols="40" id="id_title" name="title" rows="10" required="" style="resize:none;width:670px;height:34px">{{ entry.title }}</textarea>
        <br/>
        <h4 class="modal-title">内容:</h4>
        <br/>
        <textarea class="form-control" id="id_text" style="resize:none;width:670px; height:250px" name="text" cols="80" rows="10" required="" >{{ entry.text }}</textarea>
        <script>
            CKEDITOR.replace('text',{toolbar:[['Styles','Format'],['Undo','Redo'],['Cut','Copy','Paste','PasteText'],['Bold','Italic','Underline','Strike'],['NumberedList','BulletedList'],['-','Preview','/'],['Font','FontSize','TextColor'],['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','BidiLtr','BidiRtl'],['HorizontalRule','Smiley','SpecialChar','-','Maximize','Source','-'],[]]});
        </script>

        <hr>
        <button class="button button-rounded button-inverse" name="submit">保存修改</button>
        <button type="button" class="button button-rounded button-inverse" data-dismiss="modal">关闭</button>
    </form>
</div>
<script>
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});
</script>

learning_logs/templates/edit_entry2.html
{% extends "base.html" %}

{% block header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}


    <form action="{% url 'learning_logs:edit_entry2' entry.id %}" method='post'>
        {% csrf_token %}
        <h4>标题：</h4>
        <textarea class="form-control" cols="40" id="id_title" name="title" rows="10" required="" style="resize:none;width:670px;height:34px">{{ entry.title }}</textarea>
        <h4>内容:</h4>
        <textarea class="form-control" cols="40" id="id_text" name="text" rows="10" required="" style="resize:none;width:670px;height:250px">{{ entry.text }}</textarea>
        <hr>
        <button class="button button-rounded button-inverse" name="submit">保存修改</button>
    </form>

{% endblock content %}

learning_logs/templates/index.html
{% extends "base.html" %}

{% block header %}


{% endblock %}

{% block content %}
<div style="max-width:500px;margin: 0 auto;">
<img src="/static/new/images/t1.jpg"/>
</div>
<br/><br/><br/><br/>
        <h4>网站还顺便附带了笔记功能，<a href="{% url 'users:register' %}" style="color:black;">注册</a>后即可使用</h4>
        <hr/>
    <h4>除了<b>金傲城</b>还有其实一个非常**的小游戏，点一下下面的按钮就好了，欢迎挑战排行榜<small><br/>游戏由某不愿提供姓名的猫制作</small></h4>
    <h4>
        <a href="http://119.29.201.16/game/" target="_blank" id="bcat1">
            <button class="button button-rounded button-inverse">我是按钮</button>
        </a>
    </h4>
<hr/>
<audio src="media/bgm.mp3" controls="controls"></audio>
<p style="color:#999999">清廉なるHeretics</p>
{% endblock %}

learning_logs/templates/new_entry.html
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">&nbsp&nbsp标题:</h4>
</div>

<div class="modal-body" >
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        <input class="form-control" style="width:670px" name="title" id="id_title" cols="80" rows="10" required="" >
        <br/>
        <h4 class="modal-title">内容:</h4>
        <br/>
        <textarea class="form-control" id="id_text" style="resize:none;width:670px; height:250px" name="text" cols="80" rows="10" required=""></textarea>
        <script>
            CKEDITOR.replace('text',{toolbar:[['Styles','Format'],['Undo','Redo'],['Cut','Copy','Paste','PasteText'],['Bold','Italic','Underline','Strike'],['NumberedList','BulletedList'],['-','Preview','/'],['Font','FontSize','TextColor'],['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','BidiLtr','BidiRtl'],['HorizontalRule','Smiley','SpecialChar','-','Maximize','Source','-'],[]]});
        </script>

    <hr>
    <button id="new_entry" class="button button-rounded button-inverse" name="submit">添加内容</button>
    <button type="button" class="button button-rounded button-inverse" data-dismiss="modal">关闭</button>
    </form>
</div>
<script>
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});
</script>

learning_logs/templates/new_entry2.html
{% extends "base.html" %}

{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}
  <form action="{% url 'learning_logs:new_entry2' topic.id %}" method='post'>
    {% csrf_token %}
    <h4>标题：</h4>
    <input class="form-control" style="width:670px" name="title" id="id_title" cols="80" rows="10" required="" >
    <h4>内容:</h4>

    <textarea class="form-control" style="resize:none;width:670px; height:250px" name="text" id="id_text" cols="80" rows="10" required="" ></textarea>
    <hr>
    <button id="new_entry2" class="button button-rounded button-inverse" name="submit">添加内容</button>
  </form>

{% endblock content %}

learning_logs/templates/new_topic.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">&nbsp新建主题:</h4>
</div>

<div class="modal-body" >
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    <input class="form-control" style="width:670px" name="text" id="id_text" cols="80" rows="10" required="" >
    <br/>
    <button id="new_topic" name="submit" class="button button-rounded button-inverse">确定</button>
    <button type="button" class="button button-rounded button-inverse" data-dismiss="modal">关闭</button>
  </form>
</div>

learning_logs/templates/topic.html
{% extends 'base.html' %}

{% block header %}
<h1><a href="{% url 'learning_logs:topics' %}" style="color:black;text-decoration:none;vertical-align:middle" onmouseover="this.style.text-decoration=none">{{ topic }}</a></h1>
          <!--
          <div class="btn-group">
          -->
              <button type="button" class="button button-rounded button-inverse" href="{% url 'learning_logs:new_entry' topic.id %}" data-toggle="modal" data-target="#new_entry" id="new_entry1">添加内容</button>
              <!--
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-only">切换下拉菜单</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                  <li>
                      <a href="{% url 'learning_logs:new_entry2' topic.id %}">旧版添加页面</a>
                  </li>
              </ul>
          </div>
          -->

              <div class="modal fade" id="new_entry" tabindex="-1" role="dialog" aria-labelledby="new_entry" aria-hidden="true" style="top:13%;left:3%;">
                  <div class="modal-dialog" style="width:700px">
                      <div class="modal-content"></div>
                  </div>
              </div>

{% endblock header %}

{% block content %}

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <a data-toggle="collapse" data-parent="#accordion"
                href="#{{ entry.id }}" style="color:black;text-decoration:none;vertical-align:middle" onmouseover="this.style.text-decoration=none">
          {{ entry.date_added|date:'Y-m-d D H:i' }}
          </a>
            <!--
            <a href="{% url 'learning_logs:del_entry' entry.id %}">
              删除</a>
              -->
                <!--
                <div class="btn-group">
                -->
                    <!--
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">切换下拉菜单</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="{% url 'learning_logs:edit_entry2' entry.id %}">旧版修改页面</a>
                        </li>
                    </ul>
                </div>
                -->

                <div class="modal fade" id="edit_entry" tabindex="-1" role="dialog" aria-labelledby="edit_entry" aria-hidden="true" style="top:13%;left:3%;">
                    <div class="modal-dialog" style="width:700px">
                        <div class="modal-content"></div>
                    </div>
                </div>
        </h3>
      </div>

       <div id="{{ entry.id }}" class="panel-collapse collapse">
        <div class="panel-body">
        <h3>
          {{ entry.title }}
        </h3>
        <hr/>
            <div style="max-width:600px;margin: 0 auto;text-align:left;">
        {% autoescape off %}
        {{ entry.text|linebreaks }}
        {% endautoescape %}
            </div>
        <button type="button" class="button button-tiny" href="{% url 'learning_logs:edit_entry' entry.id %}" data-toggle="modal" data-target="#edit_entry">修改</button>
      </div>
       </div>
    </div> <!-- panel -->


  {% empty %}
    该主题目前没有添加内容
  {% endfor %}

{% endblock content %}

learning_logs/templates/topics.html
{% extends "base.html" %}

{% block header %}
  <h1>主题</h1>
<a class="button button-rounded button-inverse" href="{% url 'learning_logs:new_topic' %}" data-toggle="modal" data-target="#new_topic" id="new_topic1">新建主题</a>

      <div class="modal fade" id="new_topic" tabindex="-1" role="dialog" aria-labelledby="new_topic" aria-hidden="true" style="top:20%;left:3%;">
      <div class="modal-dialog" style="width:700px">
        <div class="modal-content"></div>
      </div>
    </div>

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
{% for topic in topics %}

    <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}" style="color:black;text-decoration:none;" onmouseover="this.style.text-decoration=none">{{ topic }}</a>
          <br/>
          <small>
          {{ topic.date_added|date:'Y-m-d D H:i' }}
          </small>
        </h3>
      </div>
    </div>
    </div>

    {% empty %}
      <li>目前没有任何主题</li>
{% endfor %}

    </div>
</div>

{% endblock content %}